/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AssetAnalysisSchema extends BaseModel {
  static $columns = ['assetId', 'cacheKey', 'createdAt', 'id', 'model', 'ocrText', 'palette', 'promptVersion', 'raw', 'status', 'summary', 'tags', 'tokensIn', 'tokensOut'] as const
  $columns = AssetAnalysisSchema.$columns
  @column()
  declare assetId: number
  @column()
  declare cacheKey: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare model: string
  @column()
  declare ocrText: string | null
  @column()
  declare palette: any | null
  @column()
  declare promptVersion: string | null
  @column()
  declare raw: any | null
  @column()
  declare status: string
  @column()
  declare summary: string | null
  @column()
  declare tags: any | null
  @column()
  declare tokensIn: number | null
  @column()
  declare tokensOut: number | null
}

export class AssetSchema extends BaseModel {
  static $columns = ['analysisKey', 'boardId', 'createdAt', 'filename', 'height', 'id', 'kind', 'mime', 'position', 'sha256', 'size', 'source', 'storageKey', 'thumbKey', 'userNote', 'width'] as const
  $columns = AssetSchema.$columns
  @column()
  declare analysisKey: string | null
  @column()
  declare boardId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare filename: string
  @column()
  declare height: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare kind: string
  @column()
  declare mime: string | null
  @column()
  declare position: any | null
  @column()
  declare sha256: string | null
  @column()
  declare size: bigint | number | null
  @column()
  declare source: string | null
  @column()
  declare storageKey: string | null
  @column()
  declare thumbKey: string | null
  @column()
  declare userNote: string | null
  @column()
  declare width: number | null
}

export class BoardSceneSchema extends BaseModel {
  static $columns = ['appState', 'boardId', 'createdAt', 'document', 'id', 'updatedAt', 'version'] as const
  $columns = BoardSceneSchema.$columns
  @column()
  declare appState: any
  @column()
  declare boardId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare document: any
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare version: number
}

export class BoardSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'slug', 'title', 'updatedAt', 'userId'] as const
  $columns = BoardSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare slug: string
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class CreditGrantSchema extends BaseModel {
  static $columns = ['amount', 'createdAt', 'expiresAt', 'externalId', 'id', 'remaining', 'revokedAt', 'source', 'userId'] as const
  $columns = CreditGrantSchema.$columns
  @column()
  declare amount: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare externalId: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare remaining: number
  @column.dateTime()
  declare revokedAt: DateTime | null
  @column()
  declare source: string
  @column()
  declare userId: number
}

export class CreditTransactionSchema extends BaseModel {
  static $columns = ['amount', 'createdAt', 'designDocId', 'designPreviewId', 'grantId', 'id', 'kind', 'note', 'userId'] as const
  $columns = CreditTransactionSchema.$columns
  @column()
  declare amount: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare designDocId: number | null
  @column()
  declare designPreviewId: number | null
  @column()
  declare grantId: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare kind: string
  @column()
  declare note: string | null
  @column()
  declare userId: number
}

export class DesignDocSchema extends BaseModel {
  static $columns = ['boardId', 'contentMd', 'createdAt', 'creditsCharged', 'error', 'generatedAt', 'id', 'inputFingerprint', 'jobId', 'model', 'proMode', 'promptVersion', 'sources', 'spec', 'status', 'usage', 'version'] as const
  $columns = DesignDocSchema.$columns
  @column()
  declare boardId: number
  @column()
  declare contentMd: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare creditsCharged: number | null
  @column()
  declare error: string | null
  @column.dateTime()
  declare generatedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare inputFingerprint: string | null
  @column()
  declare jobId: number | null
  @column()
  declare model: string | null
  @column()
  declare proMode: boolean
  @column()
  declare promptVersion: string | null
  @column()
  declare sources: any | null
  @column()
  declare spec: any | null
  @column()
  declare status: string
  @column()
  declare usage: any | null
  @column()
  declare version: number
}

export class DesignPreviewSchema extends BaseModel {
  static $columns = ['createdAt', 'creditsCharged', 'designDocId', 'error', 'generatedAt', 'html', 'id', 'jobId', 'model', 'status'] as const
  $columns = DesignPreviewSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare creditsCharged: number | null
  @column()
  declare designDocId: number
  @column()
  declare error: string | null
  @column.dateTime()
  declare generatedAt: DateTime | null
  @column()
  declare html: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare jobId: number | null
  @column()
  declare model: string | null
  @column()
  declare status: string
}

export class JobSchema extends BaseModel {
  static $columns = ['attempts', 'createdAt', 'id', 'lastError', 'lockedAt', 'payload', 'runAt', 'status', 'type', 'updatedAt'] as const
  $columns = JobSchema.$columns
  @column()
  declare attempts: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare lastError: string | null
  @column.dateTime()
  declare lockedAt: DateTime | null
  @column()
  declare payload: any
  @column.dateTime()
  declare runAt: DateTime | null
  @column()
  declare status: string
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class SubscriptionSchema extends BaseModel {
  static $columns = ['createdAt', 'customerId', 'endsAt', 'externalId', 'id', 'plan', 'provider', 'renewsAt', 'status', 'updatedAt', 'userId', 'variantId'] as const
  $columns = SubscriptionSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare customerId: string | null
  @column.dateTime()
  declare endsAt: DateTime | null
  @column()
  declare externalId: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare plan: string
  @column()
  declare provider: string
  @column.dateTime()
  declare renewsAt: DateTime | null
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
  @column()
  declare variantId: string | null
}

export class UserTokenSchema extends BaseModel {
  static $columns = ['createdAt', 'expiresAt', 'id', 'tokenHash', 'type', 'usedAt', 'userId'] as const
  $columns = UserTokenSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare tokenHash: string
  @column()
  declare type: string
  @column.dateTime()
  declare usedAt: DateTime | null
  @column()
  declare userId: number
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'emailVerifiedAt', 'fullName', 'id', 'locale', 'password', 'referralCode', 'referredById', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column.dateTime()
  declare emailVerifiedAt: DateTime | null
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare locale: string | null
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare referralCode: string | null
  @column()
  declare referredById: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
