/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AssetAnalysisSchema extends BaseModel {
  static $columns = ['assetId', 'createdAt', 'id', 'model', 'ocrText', 'palette', 'raw', 'status', 'summary', 'tags', 'tokensIn', 'tokensOut'] as const
  $columns = AssetAnalysisSchema.$columns
  @column()
  declare assetId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare model: string
  @column()
  declare ocrText: string | null
  @column()
  declare palette: any | null
  @column()
  declare raw: any | null
  @column()
  declare status: string
  @column()
  declare summary: string | null
  @column()
  declare tags: any | null
  @column()
  declare tokensIn: number | null
  @column()
  declare tokensOut: number | null
}

export class AssetSchema extends BaseModel {
  static $columns = ['analysisKey', 'boardId', 'createdAt', 'filename', 'height', 'id', 'kind', 'mime', 'position', 'sha256', 'size', 'source', 'storageKey', 'thumbKey', 'userNote', 'width'] as const
  $columns = AssetSchema.$columns
  @column()
  declare analysisKey: string | null
  @column()
  declare boardId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare filename: string
  @column()
  declare height: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare kind: string
  @column()
  declare mime: string | null
  @column()
  declare position: any | null
  @column()
  declare sha256: string | null
  @column()
  declare size: bigint | number | null
  @column()
  declare source: string | null
  @column()
  declare storageKey: string | null
  @column()
  declare thumbKey: string | null
  @column()
  declare userNote: string | null
  @column()
  declare width: number | null
}

export class BoardSceneSchema extends BaseModel {
  static $columns = ['appState', 'boardId', 'document', 'id', 'updatedAt', 'version'] as const
  $columns = BoardSceneSchema.$columns
  @column()
  declare appState: any
  @column()
  declare boardId: number
  @column()
  declare document: any
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare version: number
}

export class BoardSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'slug', 'title', 'updatedAt', 'userId'] as const
  $columns = BoardSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare slug: string
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class DesignDocSchema extends BaseModel {
  static $columns = ['boardId', 'contentMd', 'error', 'generatedAt', 'id', 'inputFingerprint', 'model', 'promptVersion', 'status', 'version'] as const
  $columns = DesignDocSchema.$columns
  @column()
  declare boardId: number
  @column()
  declare contentMd: string | null
  @column()
  declare error: string | null
  @column.dateTime()
  declare generatedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare inputFingerprint: string | null
  @column()
  declare model: string | null
  @column()
  declare promptVersion: string | null
  @column()
  declare status: string
  @column()
  declare version: number
}

export class JobSchema extends BaseModel {
  static $columns = ['attempts', 'id', 'lastError', 'lockedAt', 'payload', 'runAt', 'status', 'type'] as const
  $columns = JobSchema.$columns
  @column()
  declare attempts: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare lastError: string | null
  @column.dateTime()
  declare lockedAt: DateTime | null
  @column()
  declare payload: any
  @column.dateTime()
  declare runAt: DateTime | null
  @column()
  declare status: string
  @column()
  declare type: string
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'password', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
