import type { DesignSpec } from '#services/design/spec'
import { renderCssVariables, renderTailwindTheme } from '#services/design/renderer'

/**
 * Eksport tokenów w formacie W3C Design Tokens (DTCG): kolory, rodziny fontów,
 * skala typografii, odstępy, promienie i cienie. Czytają go Style Dictionary,
 * Tokens Studio i wtyczki Figmy.
 */

type Token = { $type: string; $value: unknown; $description?: string }
type Group = Record<string, Token>

function key(value: string): string {
  return (
    value
      .toLowerCase()
      .replace(/^--/, '')
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-|-$/g, '') || 'token'
  )
}

function unique(group: Group, name: string): string {
  let candidate = key(name)
  for (let i = 2; candidate in group; i++) candidate = `${key(name)}-${i}`
  return candidate
}

export function renderDesignTokens(spec: DesignSpec): Record<string, unknown> {
  const color: Group = {}
  for (const c of spec.colors) {
    color[unique(color, c.name)] = { $type: 'color', $value: c.hex, $description: c.role }
  }

  const fontFamily: Group = {}
  for (const f of spec.typography.families) {
    fontFamily[unique(fontFamily, f.name)] = {
      $type: 'fontFamily',
      $value: [f.name, ...(f.substitute ? [f.substitute] : []), 'sans-serif'],
      $description: f.role,
    }
  }

  const typography: Group = {}
  for (const row of spec.typography.scale) {
    typography[unique(typography, row.role)] = {
      $type: 'typography',
      $value: {
        fontFamily: row.family,
        fontWeight: Number.parseInt(row.weight, 10) || row.weight,
        fontSize: row.size,
        lineHeight: row.lineHeight === '—' ? undefined : row.lineHeight,
        letterSpacing: row.letterSpacing === '—' ? undefined : row.letterSpacing,
      },
    }
  }

  const dimension = (items: { name: string; value: string }[]): Group => {
    const group: Group = {}
    for (const item of items)
      group[unique(group, item.name)] = { $type: 'dimension', $value: item.value }
    return group
  }

  const shadow: Group = {}
  for (const s of spec.shadows)
    shadow[unique(shadow, s.name)] = { $type: 'shadow', $value: s.value }

  return {
    $description: `${spec.name} — design tokens generated by canvai`,
    color,
    fontFamily,
    typography,
    spacing: dimension(spec.spacing.scale),
    radius: dimension(spec.radii),
    shadow,
  }
}

export type ExportFormat = 'css' | 'tailwind' | 'tokens'

/** Plik eksportu (nazwa, typ, treść) — wspólny dla UI, REST v1 i MCP. */
export function renderExport(spec: DesignSpec, format: ExportFormat) {
  switch (format) {
    case 'css':
      return { name: 'tokens.css', type: 'text/css', body: renderCssVariables(spec) + '\n' }
    case 'tailwind':
      return {
        name: 'theme.css',
        type: 'text/css',
        body: `@import "tailwindcss";\n\n${renderTailwindTheme(spec)}\n`,
      }
    case 'tokens':
      return {
        name: 'design-tokens.json',
        type: 'application/json',
        body: JSON.stringify(renderDesignTokens(spec), null, 2) + '\n',
      }
  }
}
