import type { DesignSpec } from '#services/design/spec'
import { renderCssVariables, renderTailwindTheme } from '#services/design/renderer'

/**
 * Eksport tokenów w formacie W3C Design Tokens (DTCG): kolory, rodziny fontów,
 * skala typografii, odstępy, promienie i cienie. Czytają go Style Dictionary,
 * Tokens Studio i wtyczki Figmy.
 */

type Token = { $type: string; $value: unknown; $description?: string }
type Group = Record<string, Token>

function key(value: string): string {
  return (
    value
      .toLowerCase()
      .replace(/^--/, '')
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-|-$/g, '') || 'token'
  )
}

function unique(group: Group, name: string): string {
  let candidate = key(name)
  for (let i = 2; candidate in group; i++) candidate = `${key(name)}-${i}`
  return candidate
}

export function renderDesignTokens(spec: DesignSpec): Record<string, unknown> {
  const color: Group = {}
  for (const c of spec.colors) {
    color[unique(color, c.name)] = { $type: 'color', $value: c.hex, $description: c.role }
  }

  const fontFamily: Group = {}
  for (const f of spec.typography.families) {
    fontFamily[unique(fontFamily, f.name)] = {
      $type: 'fontFamily',
      $value: [f.name, ...(f.substitute ? [f.substitute] : []), 'sans-serif'],
      $description: f.role,
    }
  }

  const typography: Group = {}
  for (const row of spec.typography.scale) {
    typography[unique(typography, row.role)] = {
      $type: 'typography',
      $value: {
        fontFamily: row.family,
        fontWeight: Number.parseInt(row.weight, 10) || row.weight,
        fontSize: row.size,
        lineHeight: row.lineHeight === '—' ? undefined : row.lineHeight,
        letterSpacing: row.letterSpacing === '—' ? undefined : row.letterSpacing,
      },
    }
  }

  const dimension = (items: { name: string; value: string }[]): Group => {
    const group: Group = {}
    for (const item of items)
      group[unique(group, item.name)] = { $type: 'dimension', $value: item.value }
    return group
  }

  const shadow: Group = {}
  for (const s of spec.shadows)
    shadow[unique(shadow, s.name)] = { $type: 'shadow', $value: s.value }

  return {
    $description: `${spec.name} — design tokens generated by canvai`,
    color,
    fontFamily,
    typography,
    spacing: dimension(spec.spacing.scale),
    radius: dimension(spec.radii),
    shadow,
  }
}

// ---------------------------------------------------------------------------
// Pozostałe formaty: Tailwind v3, SCSS, Tokens Studio (Figma)
// ---------------------------------------------------------------------------

function cssName(token: string): string {
  return token.replace(/^--/, '')
}

/** `tailwind.config.js` (Tailwind v3) — `theme.extend` z tokenów. */
export function renderTailwindConfig(spec: DesignSpec): string {
  const colorKey = (token: string) => cssName(token).replace(/^color-/, '')
  const extend = {
    colors: Object.fromEntries(spec.colors.map((c) => [colorKey(c.token), c.hex])),
    fontFamily: Object.fromEntries(
      spec.typography.families.map((f) => [
        cssName(f.token).replace(/^font-/, ''),
        [f.name, ...(f.substitute ? f.substitute.split(',').map((x) => x.trim()) : ['sans-serif'])],
      ])
    ),
    fontSize: Object.fromEntries(
      spec.typography.scale.map((r) => [
        cssName(r.token).replace(/^text-/, ''),
        r.lineHeight === '—' ? r.size : [r.size, { lineHeight: r.lineHeight }],
      ])
    ),
    spacing: Object.fromEntries(spec.spacing.scale.map((s) => [key(s.name), s.value])),
    borderRadius: Object.fromEntries(spec.radii.map((r) => [key(r.name), r.value])),
    boxShadow: Object.fromEntries(spec.shadows.map((s) => [key(s.name), s.value])),
  }
  return [
    `/** ${spec.name} — Tailwind CSS v3 theme generated by canvai from DESIGN.md. */`,
    `/** @type {import('tailwindcss').Config} */`,
    `module.exports = {`,
    `  content: ['./src/**/*.{html,js,jsx,ts,tsx,vue,svelte,astro}'],`,
    `  theme: {`,
    `    extend: ${JSON.stringify(extend, null, 2).replace(/\n/g, '\n    ')},`,
    `  },`,
    `}`,
    '',
  ].join('\n')
}

/** Zmienne SCSS. */
export function renderScss(spec: DesignSpec): string {
  const lines = [`// ${spec.name} — design tokens generated by canvai`, '']
  const add = (title: string, entries: [string, string][]) => {
    if (!entries.length) return
    lines.push(`// ${title}`)
    for (const [k, v] of entries) lines.push(`$${k}: ${v};`)
    lines.push('')
  }
  add(
    'Colors',
    spec.colors.map((c) => [cssName(c.token), c.hex])
  )
  add(
    'Typography',
    spec.typography.families.map((f) => [
      cssName(f.token),
      `'${f.name.replace(/'/g, '')}', ${f.substitute || 'sans-serif'}`,
    ])
  )
  add(
    'Type scale',
    spec.typography.scale.map((r) => [cssName(r.token), r.size])
  )
  add(
    'Spacing',
    spec.spacing.scale.map((s) => [`spacing-${key(s.name)}`, s.value])
  )
  add(
    'Radius',
    spec.radii.map((r) => [`radius-${key(r.name)}`, r.value])
  )
  add(
    'Shadows',
    spec.shadows.map((s) => [`shadow-${key(s.name)}`, s.value])
  )
  return lines.join('\n')
}

/**
 * Tokens Studio for Figma (format JSON z `value`/`type`) — import w wtyczce
 * Tokens Studio tworzy zmienne i style w Figmie.
 */
export function renderTokensStudio(spec: DesignSpec): Record<string, unknown> {
  const set: Record<string, Record<string, unknown>> = {
    color: {},
    fontFamilies: {},
    fontSizes: {},
    lineHeights: {},
    spacing: {},
    borderRadius: {},
    boxShadow: {},
  }
  for (const c of spec.colors)
    set.color[unique(set.color as Group, c.name)] = {
      value: c.hex,
      type: 'color',
      description: c.role,
    }
  for (const f of spec.typography.families)
    set.fontFamilies[unique(set.fontFamilies as Group, f.name)] = {
      value: f.name,
      type: 'fontFamilies',
    }
  for (const r of spec.typography.scale) {
    set.fontSizes[unique(set.fontSizes as Group, r.role)] = { value: r.size, type: 'fontSizes' }
    if (r.lineHeight !== '—')
      set.lineHeights[unique(set.lineHeights as Group, r.role)] = {
        value: r.lineHeight,
        type: 'lineHeights',
      }
  }
  for (const s of spec.spacing.scale)
    set.spacing[unique(set.spacing as Group, s.name)] = { value: s.value, type: 'spacing' }
  for (const r of spec.radii)
    set.borderRadius[unique(set.borderRadius as Group, r.name)] = {
      value: r.value,
      type: 'borderRadius',
    }
  for (const sh of spec.shadows)
    set.boxShadow[unique(set.boxShadow as Group, sh.name)] = { value: sh.value, type: 'boxShadow' }
  return {
    [key(spec.name) || 'canvai']: set,
    $themes: [],
    $metadata: { tokenSetOrder: [key(spec.name) || 'canvai'] },
  }
}

// ---------------------------------------------------------------------------
// Pliki dla narzędzi AI do kodu
// ---------------------------------------------------------------------------

/**
 * Zwięzła ściągawka systemu (tokeny, typografia, zasady, dostępność) —
 * wspólna dla reguł Cursora, CLAUDE.md, AGENTS.md i promptu v0/Lovable.
 * Pełna specyfikacja zostaje w DESIGN.md.
 */
export function condensedGuide(spec: DesignSpec): string {
  const lines: string[] = []
  lines.push(`Theme: ${spec.theme}. ${spec.tagline}`.trim())
  lines.push('', '### Colors (use the tokens, never raw hex)')
  for (const c of spec.colors) lines.push(`- \`${c.token}\` ${c.hex} — ${c.name}: ${c.role}`)
  lines.push('', '### Typography')
  for (const f of spec.typography.families) {
    lines.push(
      `- \`${f.token}\`: ${f.name}${f.substitute ? ` (fallback ${f.substitute})` : ''} — ${f.role}`
    )
  }
  for (const r of spec.typography.scale) {
    lines.push(
      `- ${r.role}: ${r.size}${r.lineHeight !== '—' ? `/${r.lineHeight}` : ''}, weight ${r.weight} (\`${r.token}\`)`
    )
  }
  const shape = [
    `base unit ${spec.spacing.baseUnit} (${spec.spacing.density})`,
    ...spec.radii.map((r) => `radius ${r.name} ${r.value}`),
    ...spec.shadows.map((s) => `shadow ${s.name}: ${s.value}`),
  ]
  lines.push('', '### Spacing & shape', ...shape.map((x) => `- ${x}`))
  if (spec.components.length) {
    lines.push('', '### Components')
    for (const c of spec.components.slice(0, 14))
      lines.push(`- **${c.name}**: ${c.description.replace(/\s+/g, ' ').slice(0, 280)}`)
  }
  lines.push('', '### Do', ...spec.dos.map((d) => `- ${d}`))
  lines.push('', "### Don't", ...spec.donts.map((d) => `- ${d}`))
  lines.push(
    '',
    '### Accessibility',
    '- Body text contrast ≥ 4.5:1 (WCAG AA); visible focus ring on every interactive element.',
    '- Respect prefers-reduced-motion; hit targets ≥ 24×24px (44px on touch).'
  )
  return lines.join('\n')
}

const RULES_INTRO =
  'This project has a design system. Build every UI with its tokens and rules; the complete specification (components, states, screens, voice) is in `DESIGN.md` at the repository root — read it before creating or changing UI.'

export function renderCursorRules(spec: DesignSpec): string {
  return [
    '---',
    `description: ${spec.name} design system — tokens, typography, components and UI rules`,
    'globs: "**/*.{tsx,jsx,vue,svelte,astro,html,css,scss}"',
    'alwaysApply: false',
    '---',
    '',
    `# ${spec.name} design system`,
    '',
    RULES_INTRO,
    '',
    condensedGuide(spec),
    '',
  ].join('\n')
}

export function renderClaudeMd(spec: DesignSpec): string {
  return [
    `# Design system — ${spec.name}`,
    '',
    RULES_INTRO,
    '',
    'Full specification: @DESIGN.md',
    '',
    condensedGuide(spec),
    '',
  ].join('\n')
}

export function renderAgentsMd(spec: DesignSpec): string {
  return [
    `# AGENTS.md — UI and design system (${spec.name})`,
    '',
    RULES_INTRO,
    '',
    condensedGuide(spec),
    '',
  ].join('\n')
}

/** Prompt do wklejenia w v0 / Lovable / Bolt (bez dostępu do plików repozytorium). */
export function renderBuilderPrompt(spec: DesignSpec): string {
  return [
    `Build the UI for "${spec.name}" following this design system exactly. Use only these colors, fonts, sizes, radii and shadows (define them as CSS variables / Tailwind theme), apply the component descriptions and the do/don't rules, keep text contrast at WCAG AA.`,
    '',
    spec.overview
      .replace(/\[A\d+\]/g, '')
      .replace(/\s+/g, ' ')
      .trim(),
    '',
    condensedGuide(spec),
    '',
    'Start with the most representative screen, responsive (mobile first). Use realistic copy, no lorem ipsum.',
    '',
  ].join('\n')
}

export const EXPORT_FORMATS = [
  'css',
  'tailwind',
  'tokens',
  'tailwind3',
  'scss',
  'figma',
  'cursor',
  'claude',
  'agents',
  'prompt',
] as const

export type ExportFormat = (typeof EXPORT_FORMATS)[number]

/** Plik eksportu (nazwa, typ, treść) — wspólny dla UI, REST v1 i MCP. */
export function renderExport(spec: DesignSpec, format: ExportFormat) {
  switch (format) {
    case 'css':
      return { name: 'tokens.css', type: 'text/css', body: renderCssVariables(spec) + '\n' }
    case 'tailwind':
      return {
        name: 'theme.css',
        type: 'text/css',
        body: `@import "tailwindcss";\n\n${renderTailwindTheme(spec)}\n`,
      }
    case 'tokens':
      return {
        name: 'design-tokens.json',
        type: 'application/json',
        body: JSON.stringify(renderDesignTokens(spec), null, 2) + '\n',
      }
    case 'tailwind3':
      return {
        name: 'tailwind.config.js',
        type: 'text/javascript',
        body: renderTailwindConfig(spec),
      }
    case 'scss':
      return { name: '_tokens.scss', type: 'text/x-scss', body: renderScss(spec) }
    case 'figma':
      return {
        name: 'tokens-studio.json',
        type: 'application/json',
        body: JSON.stringify(renderTokensStudio(spec), null, 2) + '\n',
      }
    case 'cursor':
      return { name: 'design-system.mdc', type: 'text/markdown', body: renderCursorRules(spec) }
    case 'claude':
      return { name: 'CLAUDE.md', type: 'text/markdown', body: renderClaudeMd(spec) }
    case 'agents':
      return { name: 'AGENTS.md', type: 'text/markdown', body: renderAgentsMd(spec) }
    case 'prompt':
      return { name: 'prompt.txt', type: 'text/plain', body: renderBuilderPrompt(spec) }
  }
}
